name: "Rapport de bug"
description: Créer un nouveau ticket pour signaler un bug.
title: "[Bug] - <titre>"
labels:
  - bug
type: bug

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Fournissez une description claire et concise du problème.
      placeholder: Décrivez le problème...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportement attendu
      description: Décrivez ce qui aurait dû se produire.
      placeholder: Expliquez le résultat attendu...
    validations:
      required: true

  - type: textarea
    id: reprod
    attributes:
      label: Étapes de reproduction
      description: Listez les étapes nécessaires pour reproduire le problème.
      value: |
        1. Aller sur « ... »
        2. Cliquer sur « ... »
        3. Effectuer « ... »
        4. Observer le problème
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Quelle version du logiciel est concernée ?
      placeholder: 'Par exemple : v1.2.3'
    validations:
      required: true

  - type: textarea
    id: api_details
    attributes:
      label: Requête et réponse de l'API
      description: Si applicable, ajoutez l'URL du endpoint concerné, le corps de la requête, la réponse et les en-têtes pertinents.
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Captures d'écran
      description: Si applicable, glissez-déposez des captures d'écran pour aider à expliquer le problème.
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Journaux
      description: Collez les journaux pertinents. Ils seront automatiquement formatés comme du code.
      render: bash
    validations:
      required: false

  - type: dropdown
    id: browsers
    attributes:
      label: Navigateurs
      description: Quels navigateurs sont concernés ?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Opera
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: Système d'exploitation
      description: Quels systèmes d'exploitation sont concernés ?
      multiple: true
      options:
        - Windows
        - Linux
        - macOS
    validations:
      required: false
