CREATE TABLE vocabulary_type
(
    vocabulary_type_id INT GENERATED BY DEFAULT AS IDENTITY,
    label              VARCHAR UNIQUE NOT NULL, -- opentheso, opentypo, etc...

    PRIMARY KEY (vocabulary_type_id)
);

CREATE TABLE vocabulary
(
    vocabulary_id   INT GENERATED BY DEFAULT AS IDENTITY,
    fk_type_id      INT            NOT NULL,
    uri             VARCHAR UNIQUE NOT NULL,
    vocabulary_name VARCHAR        NOT NULL,

    PRIMARY KEY (vocabulary_id),
    FOREIGN KEY (fk_type_id) REFERENCES vocabulary_type (vocabulary_type_id)
);

CREATE TABLE vocabulary_collection
(
    vocabulary_collection_id INT GENERATED BY DEFAULT AS IDENTITY,
    ark                      VARCHAR UNIQUE NOT NULL,
    fk_vocabulary_id         INT            NOT NULL,
    collection_name          VARCHAR        NOT NULL,

    PRIMARY KEY (vocabulary_collection_id),
    FOREIGN KEY (fk_vocabulary_id) REFERENCES vocabulary (vocabulary_id)
);

CREATE TABLE concept -- TODO : properly define this table which is just a placeholder for opentheso/opentypo relationships now.
(
    concept_id         INT GENERATED BY DEFAULT AS IDENTITY,
    fk_vocabulary_id   INT            NOT NULL,
    ark                VARCHAR UNIQUE NOT NULL,
    label              VARCHAR        NOT NULL, -- on veut ajouter les labels dans differentes langues?
    concept_definition VARCHAR        NOT NULL, -- on veut ajouter les def dans differentes langues?

    PRIMARY KEY (concept_id),
    FOREIGN KEY (fk_vocabulary_id) REFERENCES vocabulary (vocabulary_id)
);

CREATE TABLE spatial_unit
(
    spatial_unit_id        INT GENERATED BY DEFAULT AS IDENTITY,
    name                   VARCHAR NOT NULL,
    gis                    VARCHAR, -- todo : define
    fk_concept_category_id INT,

    PRIMARY KEY (spatial_unit_id),
    FOREIGN KEY (fk_concept_category_id) REFERENCES concept (concept_id)
);

CREATE TABLE spatial_hierarchy
(
    fk_parent_id INT,
    fk_child_id  INT,

    PRIMARY KEY (fk_parent_id, fk_child_id),
    FOREIGN KEY (fk_parent_id) REFERENCES spatial_unit (spatial_unit_id),
    FOREIGN KEY (fk_child_id) REFERENCES spatial_unit (spatial_unit_id)
);

CREATE TABLE action_unit
(
    action_unit_id INT GENERATED BY DEFAULT AS IDENTITY,
    fk_type        INT,

    PRIMARY KEY (action_unit_id),
    FOREIGN KEY (fk_type) REFERENCES concept (concept_id)
);

CREATE TABLE siamois_user
(
    user_id            INT GENERATED BY DEFAULT AS IDENTITY,
    username           VARCHAR NOT NULL,
    password           VARCHAR NOT NULL,
    is_active          BOOLEAN DEFAULT TRUE,
    mail               VARCHAR,
    pass_to_modify     BOOLEAN DEFAULT FALSE,
    alert_mail         BOOLEAN DEFAULT FALSE,
    is_super_admin     BOOLEAN DEFAULT FALSE,
    api_key            VARCHAR,
    key_never_expire   BOOLEAN DEFAULT FALSE,
    key_expires_at     TIMESTAMPTZ,
    is_service_account BOOLEAN DEFAULT FALSE,
    key_description    VARCHAR,

    PRIMARY KEY (user_id)
);

CREATE TABLE siamois_document
(
    document_id INT GENERATED BY DEFAULT AS IDENTITY,
    title       VARCHAR, -- might be useful
    fk_nature   INT,
    fk_scale    INT,
    -- author TODO : tbd
    fk_format   INT,
    fk_parent   INT,
    --localisation_document       VARCHAR,TODO : tbd
    --metadata_document           TEXT,TODO : tbd
    --stockage_document           VARCHAR,TODO : tbd
    --license_document            TEXT,TODO : tbd
    --statut_document             VARCHAR,TODO : tbd

    PRIMARY KEY (document_id),
    FOREIGN KEY (fk_scale) REFERENCES concept (concept_id),
    FOREIGN KEY (fk_nature) REFERENCES concept (concept_id),
    FOREIGN KEY (fk_format) REFERENCES concept (concept_id),
    FOREIGN KEY (fk_parent) REFERENCES siamois_document (document_id)
);

CREATE TABLE recording_unit
(
    recording_unit_id  INT GENERATED BY DEFAULT AS IDENTITY, -- TODO: Think about ARK, should we use ARK as id?
    fk_type            INT,
    begin_date         TIMESTAMPTZ,
    end_date           TIMESTAMPTZ,
    fk_action_unit_id  INT,
    fk_spatial_unit_id INT,
    -- geospatial_extent   , -- TODO : Lien avec le SIG

    PRIMARY KEY (recording_unit_id),
    FOREIGN KEY (fk_type) REFERENCES concept (concept_id),
    FOREIGN KEY (fk_action_unit_id) REFERENCES action_unit (action_unit_id),
    FOREIGN KEY (fk_spatial_unit_id) REFERENCES spatial_unit (spatial_unit_id)
);

CREATE TABLE recording_unit_media
(
    fk_media_id          INT,
    fk_recording_unit_id INT,

    PRIMARY KEY (fk_media_id, fk_recording_unit_id),
    FOREIGN KEY (fk_media_id) REFERENCES siamois_document (document_id),
    FOREIGN KEY (fk_recording_unit_id) REFERENCES recording_unit (recording_unit_id)
);

CREATE TABLE recording_unit_group
(
    fk_parent_id INT,
    fk_child_id  INT,

    PRIMARY KEY (fk_parent_id, fk_child_id),
    FOREIGN KEY (fk_parent_id) REFERENCES recording_unit (recording_unit_id),
    FOREIGN KEY (fk_child_id) REFERENCES recording_unit (recording_unit_id)
);


CREATE TABLE stratigraphic_relationship
(
    fk_recording_unit_1_id     INT,
    fk_recording_unit_2_id     INT,
    fk_relationship_concept_id INT,

    -- TODO : constraint about the RU ids ? if relationship RU1 -> RU2 exists, don't allow for RU2 -> RU1 ?
    PRIMARY KEY (fk_recording_unit_1_id, fk_recording_unit_2_id),
    FOREIGN KEY (fk_recording_unit_1_id) REFERENCES recording_unit (recording_unit_id),
    FOREIGN KEY (fk_recording_unit_2_id) REFERENCES recording_unit (recording_unit_id),
    FOREIGN KEY (fk_relationship_concept_id) REFERENCES concept (concept_id)
);

CREATE TABLE recording_unit_study
(
    recording_unit_study_id INT GENERATED BY DEFAULT AS IDENTITY,
    author                  INT, -- TODO : link to author or user
    study_date              TIMESTAMPTZ,
    fk_method               INT,
    fk_action_unit_id       INT,
    fk_recording_unit_id    INT,

    PRIMARY KEY (recording_unit_study_id),
    FOREIGN KEY (fk_method) REFERENCES concept (concept_id),
    FOREIGN KEY (fk_action_unit_id) REFERENCES action_unit (action_unit_id),
    FOREIGN KEY (fk_recording_unit_id) REFERENCES recording_unit (recording_unit_id)
);

CREATE TABLE ru_study_document
(
    fk_document_id INT,
    fk_ru_study_id INT,

    PRIMARY KEY (fk_document_id, fk_ru_study_id),
    FOREIGN KEY (fk_document_id) REFERENCES siamois_document (document_id),
    FOREIGN KEY (fk_ru_study_id) REFERENCES recording_unit_study (recording_unit_study_id)
);

CREATE TABLE ru_study_typology
(
    fk_ru_study_id          INT,
    fk_typologie_concept_id INT,

    PRIMARY KEY (fk_ru_study_id, fk_typologie_concept_id),
    FOREIGN KEY (fk_typologie_concept_id) REFERENCES concept (concept_id),
    FOREIGN KEY (fk_ru_study_id) REFERENCES recording_unit_study (recording_unit_study_id)
);

CREATE TABLE specimen
(
    specimen_id          INT GENERATED BY DEFAULT AS IDENTITY,
    fk_recording_unit_id INT,
    -- todo : morphometrie INT ?
    -- todo : morphometrie INT ?
    fk_specimen_category INT,
    -- todo : traitement INT
    -- todo : clarify relationship between specimen and specimec study. On Miro: N to N. Why?
    fk_collection_method INT,         -- todo : faut il deux champs? il est ecrit COMMENT et POURQUOI dans le miro
    collection_date      TIMESTAMPTZ, -- quand a il été prelevé
    fk_action_unit_id    INT,
    fk_spatial_unit_id   INT,
    -- location INT -- ou a t'il été prelévé todo :GIS
    -- storage -- todo : c'est quoi stockage prelevement??

    PRIMARY KEY (specimen_id),
    FOREIGN KEY (fk_recording_unit_id) REFERENCES recording_unit (recording_unit_id),
    FOREIGN KEY (fk_specimen_category) REFERENCES concept (concept_id),
    FOREIGN KEY (fk_collection_method) REFERENCES concept (concept_id),
    FOREIGN KEY (fk_action_unit_id) REFERENCES action_unit (action_unit_id),
    FOREIGN KEY (fk_spatial_unit_id) REFERENCES spatial_unit (spatial_unit_id)
);

CREATE TABLE specimen_document
(
    fk_document_id INT,
    fk_specimen_id INT,

    PRIMARY KEY (fk_document_id, fk_specimen_id),
    FOREIGN KEY (fk_document_id) REFERENCES siamois_document (document_id),
    FOREIGN KEY (fk_specimen_id) REFERENCES specimen (specimen_id)
);

CREATE TABLE specimen_movement
(
    movement_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_specimen_id       INT         NOT NULL,
    departure_date       TIMESTAMPTZ NOT NULL,
    return_date          TIMESTAMPTZ NOT NULL,
    origin_location      VARCHAR, -- todo : define
    destination_location VARCHAR, -- todo : define
    movement_reason      VARCHAR, -- todo : useful?
    handled_by           VARCHAR, -- todo : useful?
    notes                TEXT,    -- todo : useful?

    FOREIGN KEY (fk_specimen_id) REFERENCES specimen (specimen_id)
);

CREATE TABLE specimen_group
(
    specimen_group_id INT GENERATED BY DEFAULT AS IDENTITY,
    name              VARCHAR NOT NULL,

    PRIMARY KEY (specimen_group_id)
);

CREATE TABLE specimen_group_attribution
(
    fk_specimen_group_id INT,
    fk_specimen_id       INT,

    PRIMARY KEY (fk_specimen_group_id, fk_specimen_id),
    FOREIGN KEY (fk_specimen_group_id) REFERENCES specimen_group (specimen_group_id),
    FOREIGN KEY (fk_specimen_id) REFERENCES specimen (specimen_id)
);

CREATE TABLE specimen_study
(
    specimen_study_id    INT GENERATED BY DEFAULT AS IDENTITY,
    --author   INT, -- TODO : Lien avec auteur
    study_date           TIMESTAMPTZ,
    fk_method            INT,
    fk_specimen_group_id INT,

    PRIMARY KEY (specimen_study_id),
    FOREIGN KEY (fk_method) REFERENCES concept (concept_id),
    FOREIGN KEY (fk_specimen_group_id) REFERENCES specimen_group (specimen_group_id)
);

CREATE TABLE specimen_study_document
(
    fk_document_id       INT,
    fk_specimen_study_id INT,

    PRIMARY KEY (fk_document_id, fk_specimen_study_id),
    FOREIGN KEY (fk_document_id) REFERENCES siamois_document (document_id),
    FOREIGN KEY (fk_specimen_study_id) REFERENCES specimen_study (specimen_study_id)
);

CREATE TABLE specimen_study_typology
(
    fk_specimen_study_id    INT,
    fk_typologie_concept_id INT,

    PRIMARY KEY (fk_specimen_study_id, fk_typologie_concept_id),
    FOREIGN KEY (fk_typologie_concept_id) REFERENCES concept (concept_id),
    FOREIGN KEY (fk_specimen_study_id) REFERENCES specimen_study (specimen_study_id)
);

CREATE TABLE log_entry
(
    log_entry_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    fk_user_id   INT,
    log_date     TIMESTAMPTZ,
    message      TEXT,
    ark          VARCHAR,


    PRIMARY KEY (log_entry_id),
    FOREIGN KEY (fk_user_id) REFERENCES siamois_user (user_id)
);

CREATE INDEX idx_log_entry_user_id ON log_entry (fk_user_id);
CREATE INDEX idx_log_entry_log_date ON log_entry (log_date);

CREATE TABLE spatial_unit_document
(
    fk_document_id     INT,
    fk_spatial_unit_id INT,

    PRIMARY KEY (fk_document_id, fk_spatial_unit_id),
    FOREIGN KEY (fk_document_id) REFERENCES siamois_document (document_id),
    FOREIGN KEY (fk_spatial_unit_id) REFERENCES spatial_unit (spatial_unit_id)
);

CREATE TABLE action_unit_document
(
    fk_document_id    INT,
    fk_action_unit_id INT,

    PRIMARY KEY (fk_document_id, fk_action_unit_id),
    FOREIGN KEY (fk_document_id) REFERENCES siamois_document (document_id),
    FOREIGN KEY (fk_action_unit_id) REFERENCES action_unit (action_unit_id)
);
